# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactNativeTemplateEzDevs' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeTemplateEzDevs
  pod 'Firebase/Core', '~> 5.15.0'

  target 'reactNativeTemplateEzDevs-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactNativeTemplateEzDevsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

